---
- src: https://github.com/carlosfrias/apigee-opdk-setup-default-settings

- src: https://github.com/carlosfrias/apigee-opdk-cassandra-repair

- src: https://github.com/carlosfrias/apigee-opdk-cassandra-rebuild

